### Cadastrar Autor
POST http://localhost:3333/api/authors
Content-Type: application/json

{
    "name": "David Luca",
    "birthDate": "1980-05-15",
    "sex": "Masculino",
    "writingGenre": "Fiction"
}

### Listar Autores
GET http://localhost:3333/api/authors

### Cadastrar Usuário
POST http://localhost:3333/api/users
Content-Type: application/json

{
    "name": "Caca Souza",
    "birthDate": "1990-10-20",
    "sex": "Feminino",
    "adress": "Rua Exemplo, 123"
}

### Listar Usuários
GET http://localhost:3333/api/users

### Cadastrar Livro
POST http://localhost:3333/api/books
Content-Type: application/json

{
    "title": "O Grande Livro",
    "synopsis": "Uma aventura épica",
    "year": 2020,
    "author": "68fec9d15cb4941194049044"
}

### Listar Livros
GET http://localhost:3333/api/books

### Realizar Empréstimo
POST http://localhost:3333/api/loans
Content-Type: application/json

{
    "user": "Maria Souza",
    "book": "68fed00ad9e7aae0ffc5c03d"
}